-- 2020-01-08
-- DATABASE QUERY PRACTICE

-- CREATE TABLE
CREATE TABLE CUSTOMER_TABLE(
    CUSTOMER_NO     VARCHAR2(15) PRIMARY KEY,
    CUSTOMER_NAME   VARCHAR2(15),
    PASSWD          VARCHAR2(64),
    PHONE_NUM       VARCHAR2(15),
    GENDER          VARCHAR2(5),
    POINT_          NUMBER
);

-- DROP TABLE
DROP TABLE CUSTOMER_TABLE;

-- LOOKUP TABLE
SELECT * FROM CUSTOMER_TABLE;

-- LOOKUP SPECIFIC COLUMN OF TABLE
SELECT CUSTOMER_NO FROM CUSTOMER_TABLE;

-- INSERT INTO TABLE
INSERT INTO CUSTOMER_TABLE VALUES(
    'CUSTOMER_NAME',
    'PASSWD',
    'PHONE_NUM',
    'GENDER',
    0 -- POIN_
);

-- UPDATE INFO
UPDATE CUSTOMER_TABLE SET CUSTOMER_NO = '2014707088' WHERE CUSTOMER_NO = '2014707073';
UPDATE CUSTOMER_TABLE SET PASSWD = 'DWEREWRT' WHERE CUSTOMER_NO = '2014707087';
UPDATE CUSTOMER_TABLE SET CUSTOMER_NAME = 'KIM-SOO-HWAB' WHERE CUSTOMER_NO = 2014707073;

-- DELETE
DELETE CUSTOMER_TABLE WHERE CUSTOMER_NO = 2014707087;

-- LOOKUP ADMIN_LIST TABLE
SELECT * FROM ADMIN_LIST;

-- COMMIT
COMMIT;
